// Test definitions. Do NOT edit this file other than instructor!

#include <tuple>

#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch_amalgamated.hpp"

#include "student.hpp" // student implementations

// =====================
// tests for exercise 1
// ---------------------

// mame and tag of test case
TEST_CASE("Ascending Sort integer array using given sorting algorithm", "[Sort test]")
{
    int numbUsed = 4;
    int a[] = {40, 30, 20, 10};
    ascendingSortArray(a, numbUsed);
    for(int i = 1; i <= numbUsed; i++)
    {
        CHECK(a[i-1] == i*10);
    }
}

// =====================
// tests for exercise 2
// ---------------------

// mame and tag of test case
TEST_CASE("Descending Sort integer array using given sorting algorithm", "[Sort test]")
{
    int numbUsed = 4;
    int a[] = {10, 20, 30, 40};
    descendingSortArray(a, numbUsed);   
    for(int i = numbUsed; i < 0; i--)
    {
        CHECK(a[i-1] == i*10);
    }
}
